### ISSUE TITLE
Remove duplication of normalize.css styles

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bitters#341]
Commit https://github.com/thoughtbot/bitters/commit/c16603e77a95472766b1b6b77bf237e4e274cc2c added styles that are [already a part of normalize.css](https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L285-L293):

```css
/**
 * 1. Correct the odd appearance in Chrome and Safari.
 * 2. Correct the outline style in Safari.
 */

[type="search"] {
  -webkit-appearance: textfield; /* 1 */
  outline-offset: -2px; /* 2 */
}
```

Since we encourage Bitters to be used alongside Normalize, there is no need for these styles to exist in Bitters:

https://github.com/thoughtbot/bitters/blob/fbcf9658803644ede02f3835c866141d3fba79d9/core/_forms.scss#L78-L80
