### ISSUE TITLE
Add support for ensuring the HTML hidden attribute hides content

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bitters#342]
CSS-Tricks has a great article on how weak the HTML `hidden` attribute is, in terms of specificity. It’d be great to add the bit styling to Bitters to ensure it hides content:

```css
[hidden] {
  display: none !important; 
}
```

https://css-tricks.com/the-hidden-attribute-is-visibly-weak/
